### PR TITLE
add Conditions Type

### PR DESCRIPTION
**Pull request by Brownymister**
This pr adds the missing Conditions type that was marked with a TODO comment.

### CODE REVIEW

**Review by mxstbr — COMMENTED** [review]
Thanks for the PR! Looking at [this doc](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/), I think there are multiple shapes a condition can take (not just the `type/name/value`)?

**Comment by Brownymister** [comment]
You are right. I should have read the docs ;) ...
Is there a better way to type this than to put all fields in one interface with an optional parameter?

**Comment by mxstbr** [comment]
I think a union would make sense here!

```
conditions?: Conditions[];

type Conditions = FrontmostApplicationConditions | DeviceCondition | ...

type FrontmostApplicationConditions = {
  type: "frontmost_application_if" | "frontmost_application_unless",
  bundle_identifiers?: string[],
  ...
}

type DeviceCondition = {
  type: "device_if" | "device_unless" | ...,
  ...
}
```

I realize that this is a lot of work, so no hard feelings if you don't want to contribute this 😅

**Comment by Brownymister** [comment]
No problem. It's a good opportunity for me to learn more about Typescript.

**Review by mxstbr — APPROVED** [review]
This is amazing! Thanks so much for tackling this 🙌

**Pull request merged**
